### ISSUE TITLE
Check button doesn't work

### ISSUE THREAD

**Issue by kaspot** [dthies/moodle-qbehaviour_adaptiveallnothing#1]
![image](https://user-images.githubusercontent.com/1519714/123063060-5b846a00-d40d-11eb-9bed-69c8d10a67c0.png)
The check button has no effect after clicking it. It would be great to fix this issue because we don't want to enable the plugin with a button that doesn't do anything. 

Thanks ;-)

**Comment by dthies** [comment]
This seems to be working for me still. Do you have any _Review settings_ enabled in the quiz? Adaptive requires some feed back to be enabled to be useful.
